# Site
name: "Stat Mania"
title: "Stat Mania Blog"
description: "পরিসংখ্যান কী ও কেন? পরিসংখ্যান আমাদের জীবনে কীভাবে কাজে লাগে? মেশিন লার্নিংয়ের সাথে পরিসংখ্যানের কী সম্পর্ক? সহজে কীভাবে পরিসংখ্যান বুঝব? এমনসব বিষয় নিয়েই সাজানো হয়েছে ওয়েবসাইটটি।"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: '/'
google_analytics: ''
disqus: mahmudblog
mailchimp-list: 'https://github.us7.list-manage.com/subscribe/post?u=fb245679a93a6d0bd6681211b&amp;id=f02c47251c'

include: ["_pages"]
permalink: /:title.sm

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    mahmud:
      name:           Mahmud
      site:           https://mahmud.statmania.info
      avatar:         /assets/images/logo.jpg
      bio:            "Abdullah Al Mahmud is a lecturer in statistics at Pabna Cadet College as well as a writer and data analyst. Pen-named Abdullah Adil Mahmud, he has written four science books and regularly writes on magazines and online."
      email:          almahmud.sbi@gmail.com
      twitter:        https://twitter.com/thinkermahmud

    sal:
      name:           Sal
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
      email:          wowthemesnet@gmail.com
      twitter:        https://twitter.com/wowthemesnet

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: mahmud
      avatar: /assets/images/logo.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]