---
title: "A List of Unnamed Probability Distributions"
format: pdf
---

# List of PMF

1. $\displaystyle f(x) = 6x(1-x); 0\le x\le 1$
2. $\displaystyle P(x) = \frac{x - 3}{6}, \quad \text{for } x = 4, 5, 6$
4. $\displaystyle P(x) = \frac{3x + 4}{21}, \quad x = 0, 1, 2$
5. $\displaystyle P(X) = \frac{3-\vert 4-x\vert}{k}; x=2,3,4,5,6$
6. $\displaystyle P(X) = \frac{5-\vert 6-x\vert}{k}; x=1,2,3,4,5$
7. $\displaystyle P(X) = \frac{7-\vert 5-x\vert}{k}; x=1,2,3,4,5,6$
8. $\displaystyle P(X) = \frac{6-|7-x|}{k}; x = 1, 2, \cdots,10$
9. $\displaystyle P(x) = \frac{x+1}{k}; x= 1,2,3,4$
10. $\displaystyle P(x) = \frac{2x+k}{56}; x = -3, -2, -1, 0, 1, 2, 3$
11. $\displaystyle P(x) = \frac{1}{14} (a+2x); x = -3, -2, -1, 0, 1, 2, 3$
12. $\displaystyle P(x) = k(x-2); x = 3, 4,5,6,7,8$
13. $\displaystyle P(x) = \frac{x-1}{k}; x=2,3,4,5$
14. $\displaystyle P(x) = \frac{3-|4-x|}{k}; x=2,3,4,5,6$
15. $\displaystyle p(x) = \frac{x+4}{30}; x=0,1,2,3,4$


## Joint PMF

1. $\displaystyle P(X,Y) = \frac{x + 2y}{28}; \quad x = 0, 1; \quad y = 0, 1, 2, 3$
2. $\displaystyle P(X,Y) = \frac{2x + 3y}{45}; \quad x = 0, 1, 2; \quad y = 0, 1, 2$
3. $\displaystyle P(X,Y) = \frac{x + y + 1}{42}; \quad x = 0, 1, 2; \quad y = 0, 1, 2, 3$
4. $\displaystyle P(X,Y) = \frac{2x + y + 1}{52}; \quad x = 1, 2; \quad y = 1, 2, 3, 4$
5. $\displaystyle P(X,Y) = \frac{3x + y}{48}; \quad x = 1, 2; \quad y = 0, 1, 2, 3$
6. $\displaystyle P(x,y) = \frac{1}{21}(x+y); x=1,2,3$ \& $y = 1,2$ 
7. $$f(x) = \frac 1 {b-a}; a\le x\le b$$


# PDF

1. $\displaystyle f(x) = 6x(1-x); 0\le x\le 1$
2. $\displaystyle f(z) = \frac29 (3z-z^2); 0 \le z \le 3$
3. $\displaystyle f(x) = k(x+1);  0 \le x \le 1$
4. $\displaystyle f(x) = kx(x-1);  1 \le x \le 4$
5. $\displaystyle  f(x) = kx^2+kx+ \frac 18; 0 \le x \le 2$
6. $\displaystyle f(x) = \frac{1}{30} (k+2x); 2 < x < 5$
7. $\displaystyle f(x) = 2x; 0 < x < 1$
8. $\displaystyle f(x) = \frac{1}{30} (3+2x); 2 < x < 5$
9. $\displaystyle f(x) = ax^2; 0 < x < 4$
10. $\displaystyle f(x) = kx; 0 < x < 4$
11. $\displaystyle f(x) = 3x^2; 0 \le x \le 1$
12. $\displaystyle f(y) = k(3y+5); 1 < y < 5$
13. $\displaystyle f(z) = \frac29 (3z-z^2); 0 \le x \le 3$