project:
  type: website
  output-dir: .

website:
  title: "Stat Mania IELTS"
  google-analytics:
    tracking-id: "G-BEELJ2ZRED"
  favicon: ../img/statmania_logo.png
  repo-url: https://github.com/mahmudstat/stat-lectures
  navbar:
    background: light
    logo: ../img/statmania_logo.png
    logo-alt: "Stat Mania Logo."
    left:
      - text: "Home"
        href: index.qmd
      - text: "Resources"
        menu:
          - text: "Hyphenated & Compound Words"
            icon: "cursor"
            href: "hyphenated-compound.qmd"
          - text: "Word Choices"
            icon: "pencil"
            href: writing-words.qmd
          - text: "External Resources"
            icon: "pencil-square"
            href: resources.qmd
      - text: "About"
        menu:
          - text: "Me"
            icon: "cursor"
            href: "https://www.thinkermahmud.com/"
          - text: "Portal"
            icon: "collection"
            href: "https://portal.statmania.info"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

  revealjs:
    theme: sky
    css:
    - slide/css/styles.css
    - styles.css
    chalkboard: true
    logo: slide/css/logo.png
    footer: docs.statmania.info | Abdullah Al Mahmud | Use space key or arrows to move slides

