---
format: html
title: "IELTS: Hyphenated & Compound words"
---

## Hyphenated words

All-knowing, brand-new, brother-in-law, check-in, check-out, commander-in-chief, cost-effective, co-worker, daughter-in-law, eco-friendly, editor-in-chief, English-speaking, energy-efficient, father-in-law, first-class, full-time, good-looking, hands-on, high-quality, high-tech, know-how, long-term, low-cost, man-made, mind-blowing, mother-in-law, ninety-nine, on-campus, once-in-a-lifetime, one-way, open-minded, part-time, passer-by, runner-up, self-employed, self-esteem, self-service, short-term, sister-in-law, son-in-law, state-of-the-art, stress-free, sugar-free, time-consuming, topsy-turvy, twenty-one, two-fold, up-to-date, user-friendly, well-developed, well-educated, well-being, well-known,


::: {.callout-tip}
Numbers between twenty-one and ninety-nine should be hyphenated when spelled out.
:::

## Compound words

airport, babysitter, backpack, bathroom, bedroom, bookshelf, brainstorm, breakfast, classroom, cupcake, daycare, doorbell, downstairs, driveway, eyelid, fireworks, fingerprint, fireman, flashlight, football, girlfriend, greenhouse, haircut, handshake, handmade, homework, housework, iceberg, keyboard, laptop, mailbox, moonlight, notebook, oatmeal, pancake, playground, raincoat, rainbow, skateboard, snowflake, snowman, softball, spaceship, sunflower, sunlight, superman, tablecloth, toothbrush, toothpaste, upstairs, wallpaper, watermelon, weekend, wheelchair, windmill, workshop, airport, armchair, backyard, basketball, bathroom, beachball, blackboard, bluebird, bodyguard, bookcase, bookmark, brainstorm, campsite, carpool, childcare, cookbook, courtyard, crosswalk, dishwasher, doorknob, earthquake, fingernail, footprint, football, greenhouse, handshake, homework, houseplant, lipstick, mailbox, milkshake, moonlight, notebook, pancake, popcorn, rainbow, shoelace, skateboard, snowball, spotlight, suitcase, sunrise, sunset, swimming pool, tablespoon, teardrop, toothbrush, toothpaste, volleyball, wheelchair, windbreaker

