project:
  type: website
  output-dir: ../

website:
  title: "Stat Mania Portal"
  google-analytics:
    tracking-id: "G-BEELJ2ZRED"
  repo-url: https://github.com/mahmudstat/stat-lectures
  navbar:
    background: light
    logo: assets/images/logo.png
    logo-alt: "Stat Mania Logo."
    left:
      - href: index.qmd
        text: Home
      - href: "https://www.statmania.info"
        text: Blog
      - text: "Study"
        menu:
          - text: "Stat Slides"
            icon: "bar-chart-fill"
            href: "https://docs.statmania.info/lectures.html"
          - text: "GRE"
            icon: "bookshelf"
            href: "/gre"
          - text: "IELTS"
            icon: "bookshelf"
            href: "/ielts"
      - text: "Resources"
        menu:
          - text: "Code Snippet"
            icon: "code"
            href: "snippets.qmd"
      - text: "Help"
        menu:
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/mahmudstat/stat-lectures/issues"
          - text: "Ask a Question"
            icon: "chat-right-text"
            href: "https://github.com/mahmudstat/stat-lectures/discussions"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true


