project:
  type: website
  output-dir: ../

website:
  title: "Stat Mania Portal"
  repo-url: https://github.com/mahmudstat/stat-lectures
  navbar:
    background: light
    logo: assets/images/logo.png
    logo-alt: "Stat Mania Logo."
    left:
      - href: index.qmd
        text: Home
      - href: "https://docs.statmania.info"
        text: Learn
      - href: "https://www.statmania.info"
        text: Blog
      - text: "Help"
        menu:
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/mahmudstat/stat-lectures/issues"
          - text: "Ask a Question"
            icon: "chat-right-text"
            href: "https://github.com/mahmudstat/stat-lectures/discussions"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true


