---
title: "Lectures"
format:
  html:
    theme: cosmo
    page-layout: full
    css: styles.css
    toc: false
---

The lectures slides have been made using [10 computer languages](index.html), including R, Bash, Latex, JavaScript, and markdown, among others.

## How to Use the presentations

- Press `space` or down-arrow ($\downarrow$) to go the next slide or see hidden contents.
- Press up-arrow ($\uparrow$) or `P` to go the previous slide.
- Press right arrow or left arrow to see next/previous chapter
- See more [here](https://defkey.com/reveal-js-shortcuts).

The `qdraw` plugin by [Abdullah Al Mahmud](https://www.thinkermahmud.com/qdraw/) is also available for all the slides, for annotation.

## First Paper

- [Introduction to Statistics](slide/01-stat-intro.html)
- [Data Collection, Organization & Presentation](slide/02-data-collection-organization-presentation.html)
- [Measures of Central Tendency](slide/03-central-tendency.html)
- [Measures of Dispersion](slide/04-dispersion.html)
- [Moments, Skewness & Kurtosis](slide/05-moments-skewness-kurtosis.html)
- [Correlation & Regression](slide/06-correlation-regression.html)
- [Time Series](slide/07-time_series.html)

## Second Paper

- [Introduction to probability](slide/01-probability-intro.html)
- [Random variable and Probability Distributions](slide/02-random-variable.html)
- [Mathematical Expectation](slide/03-expectation.html)
- [Binomial Distribution](slide/04-binomial_dist.html)
- [Poisson Distribution](slide/05-poisson_dist.html)
- [Normal Distribution](slide/6-normal-distribution.html)
- [Sampling](slide/08-sampling.html)
- [Vital Statistics](slide/09-vital-stat.html)

## Mathematics

- [Permutation-Combination](slide/permutation-combination.html)
- [Dispersion](slide/dispersion.html)
- [Probability](slide/probability.html)


## Elementary Statistics

- [VII-X Statistics and Probability](slide/elementary_stat_prob.html)

More to come...
