---
title: "Vital Statistics"
author: Abdullah Al Mahmud
date: \today
output: 
  revealjs::revealjs_presentation:
    theme: sky
    transition: zoom
    reveal_plugins: ["chalkboard", "zoom", "menu"]
    reveal_options:
      chalkboard:
        theme: whiteboard
    self_contained: false
    lib_dir: libs
    css: css/styles.css
    includes:
      in_header: css/header.html
---

# Concept of Vital Statistics

<script>
function klikaj(i) {
    document.getElementById(i).style.visibility='visible';
}
</script>

That branch of biometry which deals with data and laws of human mortality, morbidity, and demography.

**Arthur Newsholme** $\downarrow$

<blockquote>
the whole study of mankind as affected by heredity or environment in so far as the results of this study can be arithmetically stated.
</blockquote>

# Rates & Ratios

<div class="container">
<div class="col">
- Dependency Ratio 
- Sex ratio
- Population density
- Crude Birth Rate (CBR)
- General Fertility Rate (GFR)
- Age-Specific Fertility Rate (ASFR)
- Total Fertility Rate (TFR)
</div>
<div class="col">
- Gross Reproduction Rate (GRR)
- Net Reproduction Rate (NRR)
- Net Fertility Rate (NFR)
- Crude Death Rate (CDR)
- Age-Specific Death Rate (ASDR)
</div>
</div>

## Rate vs Ratio

## Dependency Ratio 

<div class="container">
<div class="col">
$$d = \frac{P_{0-14}+P_{65+}}{P_{15-64}}\times100$$
Where

- $P_{0-14}$ = The no. of children aged between 0 & 14
- $P_{65+}$ = The no. of people aged 65 or older
- $P_{15-64}$ = The no. of people aged between 15 and 64
</div>
<div class="col">
> - $d = 103\%$ means there are 103 dependents for every 100 working-age people

> - $d = 70\%$ means there 70 dependents for every 100 working-age people
</div>
</div>


## DR Example

| Age Group           | Population (millions) |
|---------------------|------------------------|
| 0-14 (Youth)        | 40                     |
| 15-64 (Working-Age) | 120                    |
| 65+ (Elderly)       | 20                     |

Find the Dependency Ratio and explain

<div onclick="klikaj('drex')"><span style="cursor:pointer;">Reveal Answer</span></div>
<div id="drex" style="visibility: hidden">
\[
\text{Dependency Ratio} = \left( \frac{\text{Youth} + \text{Elderly}}{\text{Working-age population}} \right) \times 100
\]

\[
\text{Dependency Ratio} = \left( \frac{40 + 20}{120} \right) \times 100 = \left( \frac{60}{120} \right) \times 100 = 50\%
\]
</div>



## DR Insight

Dependency Ratios of two different cities are 

$d_1 = 101\%$ and $d_2 = 98\%$

i. Which city has more dependent people per 100 working people?
2. Write the interpretation of each value.

## Sex Ratio 

$SR = \frac MF \times 100$

Suppose a town has the following population data:

- **Males**: 52,000

- **Females**: 50,000

\[
\text{Sex Ratio} = \left( \frac{\text{Number of Males}}{\text{Number of Females}} \right) \times 100
\]

\[
\text{Sex Ratio} = \left( \frac{52,000}{50,000} \right) \times 100 = 104
\]

## SR Explanation

In this example, the sex ratio is 104, which indicates that there are 104 males for every 100 females in the town.

> - IF SR = 95, what does it mean?

## Population Density

$D = \frac PA$

P = Total Population

A = Area

## Density Example

| City          | Total Population | Total Land Area (km²) |
|---------------|------------------|-----------------------|
| City A        | 1,000,000        | 500                   | 
| City B        | 2,500,000        | 1,250                 |

Find the densities

<div onclick="klikaj('popden')"><span style="cursor:pointer;">Reveal Answer</span></div>
<div id="popden" style="visibility: hidden">
\noindent \textbf{For City A:}
\[
\text{Population Density} = \frac{1,000,000}{500} = 2,000 \text{ people/km}^2
\]

\noindent \textbf{For City B:}
\[
\text{Population Density} = \frac{2,500,000}{1,250} = 2,000 \text{ people/km}^2
\]

\noindent Both cities have the same population density of 2,000 people per square kilometer.
</div>

## Density Example 02

| City             | Total Population | Total Land Area (km²) |
|:------------------:|:------------------:|:------------------------:|
| Tokyo, Japan     | 37,435,191       | 2,194                  |
| New York City, USA | 8,804,190      | 783                    |
| Mumbai, India    | 20,667,656       | 603                    |

<div onclick="klikaj('popd2')"><span style="cursor:pointer;">Reveal Answer</span></div>
<div id="popd2" style="visibility: hidden">

|       City        |     Population Density (people/km²)     |
|:-----------------:|:---------------------------------------:|
|   Tokyo, Japan    |                17,063                   |
| New York City, USA|                11,243                   |
|   Mumbai, India   |                34,285                   |


</div>
<script>
function klikaj(i) {
    document.getElementById(i).style.visibility='visible';
}
</script>

## Crude Birth Rate

$CBR = \frac BP\times 1000$

B = Total no. of alive children in a year

P = Average/Mid-year population of that region in that time

## CBR Example

If a country has 500,000 live births in a year and a mid-year population of 50,000,000:

<div onclick="klikaj('cbrex')"><span style="cursor:pointer;">Reveal Solution</span></div>
<div id="cbrex" style="visibility: hidden">
\[
\text{CBR} = \left( \frac{500,000}{50,000,000} \right) \times 1,000 = 10 \text{ births per 1,000 people}
\]
</div>

> - Explanation: There are 10 live births per 1,000 people in the population per year.

## General Fertility Rate

GFR is used to estimate the number of live births in a year per 1,000 women of childbearing age (typically ages 15-49) 

$\displaystyle GFR = \frac{B}{F_{15-49}}\times 1000$

B = Total number of live births in a year

$F_{15-49}$ = Total number of women in reproductive age group (15-49)

## GFR Example

A country has:

- Number of live births in a year: 300,000
- Number of women aged 15-49: 10,000,000

<div onclick="klikaj('gfrex')"><span style="cursor:pointer;">Reveal Answer</span></div>
<div id="gfrex" style="visibility: hidden">
\[
\text{GFR} = \left( \frac{300,000}{10,000,000} \right) \times 1,000 = 30 \text{ births per 1,000 women}
\]
</div>

> - Therefore, the General Fertility Rate in this example is 30 births per 1,000 women of childbearing age.


## Age-Specific Fertility Rate

**ASFR** is used to analyze fertility patterns across different age groups

$\displaystyle ASFR_i = \frac{B_i}{F_i}\times 1000$

$B_i$ = Total number of live births in a year by the women in ith age group

$F_i$ = No. of women in ith age group

## Total Fertility Rate

Total Fertility Rate (TFR) of a population is the average number of children that are born to a woman over her lifetime if:

i. they were to experience the exact current age-specific fertility rates (ASFRs) through their lifetime.
ii. they were to live from birth until the end of their reproductive life.

$\displaystyle TFR = 5 \sum_{i=1}^7ASFR_i = 5 \sum_{i=1}^7 \frac{B_i}{F_i}\times 1000$

5 for class interval

## Uses of Fertility Rates 

| Fertility Rate | Use Case                                             |
|-----------------|------------------------------------------------------|
| GFR             | Measures fertility of women aged 15-49               |
| ASFR            | Analyzes fertility rate specific to age groups       |
| TFR             | Estimates total children a woman would have          |
| GRR             | Measures the number of daughters born to women      |
| NRR             | Measures net reproduction rate, accounting for mortality |
| NFR             | Measures fertility rate in a given population        |

## Gross Reproduction Rate

$\displaystyle GRR = 5 \sum_{i=1}^7\frac{G_i}{F_i}\times 1000$

$G_i =$ Total number of girl babies born in a year by the women in ith age group

## Net Reproduction Rate

$\displaystyle NRR = 5 \sum_{i=1}^7\frac{G_i}{F_i}\times S_i\times 1000$

$S_i =$ Survival rate of women of reproductive age group (15-49)

## Net Fertility Rate

$\displaystyle NFR = 5 \sum_{i=1}^7\frac{B_i}{F_i}\times S_i\times 1000$

## GRR Implications

> - GRR = 1: Replacement level (each woman has, on average, one daughter).
> - GRR > 1: More than one daughter per woman on average, suggesting potential population growth.
> - GRR < 1: Fewer than one daughter per woman on average, indicating a population decline in the long term (if other factors remain constant).

## NRR Implications

> - NRR = 1: The population is at replacement level, meaning each woman has, on average, one daughter who survives to reproductive age.

> - NRR > 1: More than one daughter survives per woman, indicating the population is growing over time.

> - NRR < 1: Fewer than one daughter survives per woman, suggesting the population is declining in the long term.

## Implications

> - GRR > 1: Number of potent women increasing
> - GRR = 1: Number of potent women remains constant. There is no change in population
> - NRR > 1: The number of potent women more than that of previous year; population increasing
> - NRR = 1: No change in population
> - GRR = NRR: No new-born girls dies before reaching last potent age

# Numerical Problem

## Find CBR, GFR, ASFR, TFR, GRR, & NRR

|  Age  | # Women | # Newborn | # Baby boys | Survival probability |
|:-----:|:-------:|:---------:|:-----------:|:--------------------:|
| 15-19 |   7806000   |   521435  |    272342   |         0.980        |
| 20-24 |   6781000   |   846256  |    422247   |         0.977        |
| 25-29 |   5840000   |   412342  |    206122   |         0.972        |
| 30-34 |   5434000   |   326268  |    183134   |         0.960        |
| 35-39 |   5675000   |   211810  |    111440   |         0.942        |
| 40-44 |   6083000   |   69750   |    34380    |         0.895        |
| 45-49 |   5361000   |   42354   |    22462    |         0.854        |

Total population = 109,027,142

## Solutio to Rates

<small>

| Age Group | # Women $\times 1000$ $F_i$ | # Newborn $B_i$ | # Baby boys | # Baby girls $G_i$ | Survival probability $S_i$ | $ASFR_i =$ $\frac{B_i}{F_i}\times 1000$ | $\frac{G_i}{F_i}$ | $\frac{G_i}{F_i}\times S_i$ |
|:---------:|:-------------:|:---------------:|:-----------:|--------------------|:--------------------------:|----------------------------------------|-------------------|-----------------------------|
|   15-19   |      7806     |      521435     |    272342   |                    |            0.980           |                                        |                   |                             |
|   20-24   |      6781     |      846256     |    422247   |                    |            0.977           |                                        |                   |                             |
|   25-29   |      5840     |      412342     |    206122   |                    |            0.972           |                                        |                   |                             |
|   30-34   |      5434     |      326268     |    183134   |                    |            0.960           |                                        |                   |                             |
|   35-39   |      5675     |      211810     |    111440   |                    |            0.942           |                                        |                   |                             |
|   40-44   |      6083     |      69750      |    34380    |                    |            0.895           |                                        |                   |                             |
|   45-49   |      5361     |      42354      |    22462    |                    |            0.854           |                                        |                   |                             |
</small>

# Natural Growth Rate (NGR)

NGR = CBR - CDR

$\displaystyle \frac BP \times 1000-\frac DP \times 1000 = \frac {B-D}P \times 1000$

# Growths

## Geometric Growth

$P_o =$ Initial population

$P_n =$ Final population

$n =$ Number of period (year, month, etc)

$r =$ Rate of increase

> - Population after 1 year, $P_1 = P_o + P_or = P_o(1+r)$
> - Population after 2 years, $P_2 = P_1 + P_1r = P_1(1+r) = P_o(1+r)^2$
> - Population after n years, $P_n = P_o(1+r)^n$

## Growth Problems

- Time required for population to get doubled/tripled in certain rate
- Rate required for population to get doubled/tripled in certain time

## Exponential Growth 

Geometric: $P_n = P_o(1+r)^n$

If n is fragmented in smaller periods

Like 100 % in 1 year $\rightarrow$ 50 % in each half-year

$P_n = P_o(1+\frac{r}{n})^n$