---
title: "Measures of Dispersion"
author: Abdullah Al Mahmud
date: today
output:
  revealjs::revealjs_presentation:
    theme: sky
    transition: zoom
    reveal_plugins: ["chalkboard", "zoom", "menu"]
    reveal_options:
      chalkboard:
        theme: whiteboard
    self_contained: false
    lib_dir: libs
    css: css/styles.css
    includes:
      in_header: css/header.html
---

# Why Dispersion?

Which batter is better?

> - Batter A: 0, 100, 10, 10
> - Batter B: 20, 30, 25, 35

> - Dispersion measures variation
> - Needed alongside central tendency for comparison

# Is Dispersion Alone good?

> - Batter A: 0, 5, 10, 20, 4
> - Batter B: 10, 15, 12, 22, 16

# Graphically

<div class="container">
<div class="col">
```{r, echo=F, fig.width=6, fig.height=6}
par(bg="white")
source('rcode/sketch_circle.R')
sketch_circle()
```
</div>
<div class="col">
</br>
</br>

- Which plot has the largest dispersion?
- Which plot has the smallest dispersion?

</div>
</div>

# Which is more scattered?

> - X: 10, 12, 15, 20
> - Y: 10, 50, 170, 470

## Absolute Measures

> - Range
> - Mean Deviation
> - Quartile Deviation
> - Variance/Standard Deviation (Best)

## Relative Measures

> - Coefficient of Range
> - Coefficient of Mean Deviation
> - Coefficient of Quartile Deviation
> - Coefficient of variation (Best)

# Estimation

Data: 10, 12, 23, 16, 17, 20, 15

## Range

> - Ungrouped Data: $R = X_H - X_L$
> - Grouped Data: $R = L_n - L_1$

## Mean Deviation (MD)

Around mean, $\displaystyle MD(\bar x)=\frac{1}{n}{\sum_{i=1}^{n} |x_i - \bar{x}|}$

> - For grouped data, $\displaystyle MD(\bar x) = \frac{1}{N}{\sum_{i=1}^{n} f_i|x_i - \bar{x}|}$
> - Around Median, $\rightarrow MD (Me) = ?$
> - Around Mode, $\rightarrow MD (Mo) = ?$

## Think!

What if?

$\displaystyle MD(\bar x)=\frac{1}{n}{\sum_{i=1}^{n} (x_i - \bar{x})}$

## Grouped Data

"Classified" is not a proper term

| Class Interval | Frequency |
|:--------------:|:---------:|
| 10–19          | 5         |
| 20–29          | 12        |
| 30–39          | 18        |
| 40–49          | 10        |
| 50–59          | 6         |

## Variance and Standard Deviation

Variance, $\displaystyle \sigma^2 = \frac{1}{n} \sum_{i=1}^n (x_i - \bar{x})^2$

> - Also, $\displaystyle \sigma^2 = \frac{\sum x_i^2}{n} - \left(\frac{\sum x_i}{n}\right)^2$
> - Mean of square - square of mean
> - $\bar {x^2} - (\bar x)^2$
> - SD = $\sqrt{Variance}$
> - Why squared in the first place?

## Variance for Grouped Data

??

> - $\displaystyle \sigma^2 = \frac1n{\sum_{i=1}^{n} f_i (x_i - \bar x)^2}$ or
> - $$\displaystyle \sigma^2 = \frac{\sum f_i x_i^2}{n} - \left(\frac{\sum f_i x_i}{n}\right)^2$$
> -  Create just two columns for calculation ($f_ix_i$ and $f_ix_i^2)$

## Find Variance

| Class Interval | Mid Value (xᵢ) | Frequency (fᵢ) |$f_ix_i$|$f_ix_i^2$|
|:--------------:|:--------------:|:--------------:|:------:|:---------|
| 10–20          | 15             | 5              |        |          |
| 20–30          | 25             | 8              |        |          |
| 30–40          | 35             | 7              |        |          |

## Coefficients

> - Coefficient of Range, $CR=\frac{X_H-X_L}{X_H+X_L}\times 100$
> - Coefficient of Mean Deviation, $CMD(\bar x) = \frac{MD(\bar x)}{\bar x}$
> - Coefficient of Quartile Deviation, $QD = \frac{Q_3-Q_1}{Q_3+Q_1} \times 100$
> - Coefficient of variation (Best), $CV = \frac{\sigma}{\bar x} \times 100$

## Quartiles

Recall Median Formula

> - When $n$ is odd, $Me = \frac{n+1}{2}th$ term
> - When $n$ is even, $Me = \frac{\left(\frac{n}{2}\right)^{\text{th}} \text{ term} + \left(\frac{n}{2} + 1\right)^{\text{th}} \text{ term}}{2}$
> - Find median: 10, 20, 13
> - What now: 10, 20, 13, 11
> - Median score of 50 students is 75; what does it mean?
> - Quartiles divide the data into 4 equal parts

## Median and Quartiles Formula for Grouped Data {.smaller}

<div class="container">
<div class="col">
$\text{Median} = L + \left( \frac{\frac{N}{2} - F_c}{f_m} \right) \times h$

> - $\text{Q_3} = L + \left( \frac{\frac{3N}{4} - F_c}{f_m} \right) \times h$
</div>
<div class="col">
Where

> - $L=$ Lower boundary of the median class
> - $N=$ Total frequency
> - $F_c=$ Cumulative frequency before the median class
> - $f_m=$ Frequency of the median class
> - $h=$ Class width
</div>
</div>


## Median and Quartiles for Grouped Data

<div class="container">
<div class="col">
| Class Interval | Frequency |Cumulative Freq|
|:--------------:|:---------:|:---------:|
| 10–20          | 5         | |
| 20–30          | 11        | |
| 30–40          | 18        | |
| 40–50          | 10        | |
| 50–60          | 6         | |

$\boxed {N = 50, L = ?}$

</div>
<div class="col">

> - $Me \rightarrow \frac{N}{2}th$
> - $Q_1 \rightarrow \frac{N}{4}th$
> - $Q_3 \rightarrow \frac{3N}{4}th$
> - $F_c=?, f_m = ?,h = ?$
</div>
</div>

## Estimate CV

Given $\sigma = 4, \bar x = 10$

> - $CV = \frac{\sigma}{\bar x}\times 100$
> - $\frac{4}{10}\times 100$

## Who is better?

Marks in 5 subjects out of 30

| Student     | Mean ($\bar x$) | Standard Deviation (σ) |CV|
|:-------------:|:----------:|:------------------------:|:--:|
| A   | 20     | 3.2                    ||
| B   | 20     | 8.5                    ||
| C   | 25     | 3.2                    ||

$CV = \frac{\sigma}{\bar x}\times 100$

