---
title: "Statistics Practical"
author: Abdullah Al Mahmud
date: \today
output: 
  revealjs::revealjs_presentation:
    theme: sky
    reveal_plugins: ["chalkboard", "zoom", "menu"]
    reveal_options:
      chalkboard:
        theme: whiteboard
    self_contained: false
    lib_dir: libs
    css: css/styles.css
    includes:
      in_header: css/header.html
---

# Practical Format

- Name of the Experiment
- Problem
- Solution (after page-break)

## Solution part

- Theory/Methodology
- Equipment/Tools
- Calculation/Estimation/Computation
- Construction (if any)
- Interpretation/Explanation
- Precaution

# First Paper

# Finding Averages

Determination of Arithmetic Mean, Combined Arithmetic Mean, Geometric Mean, and Harmonic from Grouped and Ungrouped Data

# Construction of Histogram and Ogive

Name: Do

Problem: Annual profits (BDT hundred thousands) made by 115 firms are given below:

| Profit (BDT) | 25-30 | 30-35 | 35-40 | 40-45 | 45-50 | 50-55 | 55-60 |
|:------------:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|
| No. of Firms |   5   |   16  |   26  |   30  |   20  |   12  |   6   |

> - Make a histogram and Ogive from the following data and explain.

## Theory

Continuous class intervals are used for constructing histogram. Discrete class intervals are converted in the following way:

| Discrete | Continuous |
|:--------:|:----------:|
|   11-15  |  10.5-15.5 |
|   16-20  |  15.5-20.5 |

## Others

- Equipments
- Estimation (table for Ogive - cumulative frequency)

## Interpretation (Histogram)

> - Most firms earned ---
> - Few firms earned --
> - Highest profits are earned by ---
> - Lowest firms are earned by ---
> - Average profits are ---
> - Pattern of frequency 

## Interpretation (Ogive)

> - 16 firms earned 35,00,000 or less 
> - Few more like this

# Partition Values from Ogive

Name: Determination of Quartiles, Deciles, and Percentiles Using Ogive

Problem: Temperatures (in °C) of 100 cities around the world are given below:

| Temperature | 0-5 | 5-10 | 10-15 | 15-20 | 20-25 | 25-30 | 30-35 | 35-40 |
|:-----------:|:---:|:----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|
|  Frequency  |  8  |  11  |   13  |   20  |   23  |   12  |   8   |   5   |

Draw an Ogive and determine the Quartlies, 7th Decile, 35th Percentiles from the data and explain. 

# Moments

Determination of First Four Moments from Data

# Skewness-Kutosis

Determination of Skewness and Kurtosis and Their Types

# Box-plot

Construction of Box and Whisker Plot and Five Number Summary and Analyses of Their Characteristics

# Time Series

Determination of General Trend of Time Series and Prediction

# Practice Problems

## Freq Distr

Waiting times before a passenger can get a CNG auto-rickshaw from an intersection are given below. 

`r set.seed(10) sample(40:60, 15)`
