#!/usr/bin/env python3
"""Quarto pre-render hook: publish the blog's data for site.js.

On every `quarto render` (whole project or a single post) this
  * reads the front matter of posts/*.qmd and posts/*.md (title, description, date,
    tags, categories, author; `draft: true` is skipped),
  * reads authors.yml,
  * writes ../blog/site-data.json (what site.js loads in the browser),
  * copies site.js next to it, and
  * (re)writes the small authors/<slug>.qmd stubs (bio and photo are static; the
    post list is filled in by site.js).

Nothing about other posts is baked into pages, so a freshly rendered post is enough
for the archive, tag cloud, tags page, related posts and author pages to update.
"""
import html
import json
import re
import shutil
import sys
from datetime import date, datetime
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
POSTS = ROOT / "posts"
OUT_DIR = ROOT.parent / "blog"          # _quarto.yml: output-dir


def front_matter(path):
    m = re.match(r"^---\s*\n(.*?)\n---\s*(\n|$)", path.read_text(encoding="utf-8"), re.S)
    return (yaml.safe_load(m.group(1)) or {}) if m else {}


def as_date(v):
    if isinstance(v, datetime):
        return v.date()
    if isinstance(v, date):
        return v
    try:
        return datetime.strptime(str(v)[:10], "%Y-%m-%d").date()
    except ValueError:
        return None


def as_list(v, lower=False):
    if isinstance(v, str):
        v = [x.strip() for x in v.split(",")]
    out = [str(x).strip() for x in (v or []) if str(x).strip()]
    return [x.lower() for x in out] if lower else out


def load_posts():
    posts = []
    for path in sorted(list(POSTS.glob("*.qmd")) + list(POSTS.glob("*.md"))):
        if path.name.startswith("_"):
            continue
        fm = front_matter(path)
        d = as_date(fm.get("date"))
        if fm.get("draft"):
            continue
        if not fm.get("title") or d is None:
            print(f"build_site_data: skipping {path.name} (needs title and date)", file=sys.stderr)
            continue
        posts.append({
            "href": f"posts/{path.stem}.html",
            "title": str(fm["title"]),
            "desc": " ".join(str(fm.get("description") or "").split()),
            "date": d.isoformat(),
            "tags": as_list(fm.get("tags"), lower=True),
            "cats": as_list(fm.get("categories")),
            "author": str(fm.get("author") or "").strip(),
        })
    posts.sort(key=lambda p: p["date"], reverse=True)
    return posts


def load_authors():
    f = ROOT / "authors.yml"
    return (yaml.safe_load(f.read_text(encoding="utf-8")) or {}) if f.exists() else {}


def author_stub(slug, a):
    links = "".join(
        f'<a class="sm-tag" href="{html.escape(l["href"])}" rel="noopener">{html.escape(l["text"])}</a>'
        for l in a.get("links") or [])
    img = (f'<img class="sm-author-img" src="../{html.escape(a["image"])}" alt="{html.escape(a["name"])}">'
           if a.get("image") else "")
    bio = html.escape(" ".join(str(a.get("bio") or "").split()))
    tagline = " ".join(str(a.get("tagline") or "").replace('"', "'").split())
    return f"""---
title: "{a["name"]}"
description: "{tagline}"
page-layout: article
toc: false
---

<!-- GENERATED by scripts/build_site_data.py from authors.yml; do not edit. -->
```{{=html}}
<div class="sm-author-head">
{img}
<div><p class="sm-author-bio">{bio}</p>
<div class="sm-tag-cloud sm-tag-cloud-all">{links}</div></div>
</div>
<div id="sm-author-root" data-slug="{slug}"></div>
```
"""


def main():
    posts = load_posts()
    authors = load_authors()
    OUT_DIR.mkdir(exist_ok=True)
    (OUT_DIR / "site-data.json").write_text(
        json.dumps({"posts": posts, "authors": authors}, ensure_ascii=False, separators=(",", ":")),
        encoding="utf-8")
    shutil.copyfile(ROOT / "site.js", OUT_DIR / "site.js")
    (ROOT / "authors").mkdir(exist_ok=True)
    for slug, a in authors.items():
        (ROOT / "authors" / f"{slug}.qmd").write_text(author_stub(slug, a), encoding="utf-8")
    print(f"build_site_data: {len(posts)} posts, {len(authors)} authors -> blog/site-data.json")


if __name__ == "__main__":
    main()
