project:
  type: website
  output-dir: .

website:
  title: "Stat Mania GRE"
  google-analytics:
    tracking-id: "G-BEELJ2ZRED"
  favicon: ../img/statmania_logo.png
  repo-url: https://github.com/mahmudstat/stat-lectures
  navbar:
    background: light
    logo: ../img/statmania_logo.png
    logo-alt: "Stat Mania Logo."
    left:
      - href: index.qmd
        text: Home
      - href: resources.qmd
        text: Resources
      - href: ext-res.qmd
        text: External Resources
      - text: "About"
        menu:
          - text: "Me"
            icon: "cursor"
            href: "https://www.thinkermahmud.com/"
          - text: "Portal"
            icon: "collection"
            href: "https://portal.statmania.info"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">



