name: Update Cric Dashboard

on:
  schedule:
   - cron: "0 12 * * *"   # everyday 
  workflow_dispatch:        # allow manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            ggplot2
            DT
            stringr
            dplyr
            tidyr
            rvest
            quarto

      - name: Render Quarto
        run: quarto render ds/dash/rpkg.qmd --to html

      - name: Commit results
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ds/dash/
          git commit -m "Update dashboard [skip ci]" || echo "No changes to commit"
          git push
