project:
  type: website
  render:
    - "*.qmd"
    - "posts/*.qmd"
  output-dir: ../blog

website:
  title: "Stat Mania"
  description: "Posts on statistics theory, R & Python, and developer tips from Stat Mania."
  site-url: "https://www.statmania.info/blog/"
  open-graph:
    image: logo.png
  twitter-card:
    image: logo.png
  google-analytics:
    tracking-id: "G-BEELJ2ZRED"
  navbar:
    background: light
    logo: logo.png
    logo-alt: "Stat Mania Logo."
    left:
      - href: index.qmd
        text: Home
      - href: "https://www.statmania.info"
        text: Portal
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
    highlight-style: dracula
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">



