project:
  type: website
  output-dir: ../blog

website:
  title: "Stat Mania"
  google-analytics:
    tracking-id: "G-BEELJ2ZRED"
  navbar:
    background: light
    logo: logo.png
    logo-alt: "Stat Mania Logo."
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



